sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-084
env:
  global:
    -
      # LTD_AWS_ID
      secure: TBhUNITKFvhdD2Ck4i3ZIdk4cfy0PKFajl+1wQ6/BEs7FMnTGea7mb3GuC+cJTlE83zEb3tdjQ1xBnpYdHUBYe5mW/Oq9w4X8WrlfADMHnoWZI2rC5BQwt0mhlSj1biSDov5CXCXhiAsJeGJvY5NQJD6zMm3Ccn6SX6GAqBUuGAYL/2drbJD+G+sM1g79b40SjyRNSKkIgzKKqr41sO46xfkbC6HBmaQpbWnh4Ulk48dkGsIWtxz8Z6m1IBKgmlZ/zoA4DZLzSfs80r25lBuTh9v1HThy74Sjmv+ZRxaIV0WV9sRnyMoXWPSHcgCKxJHaR3VGcz8K6/Szol8It7c1Wadu94ikPodXgqhf658t8ndG56w0IusZ6CUEVa9UV3SAMSZNQwf5Wjq1Af7kRHoft3mU1k/wvXOKm3yQ/3IkF+fT5I1iNnIO4Yax0W6Q3DobBEYDHyenXIrGItI/wGuHVShehjXFz7nKbA7zn3/oqlaMd69MXiLL6NXBlKBT7W0UV/qKRr8QjUjLz4GkkrcsM3fEFNVqDcGAKomliIJTbclzsc8PJVfU13B8GPAoHTuAqvIIdX5K24AAFiXdnT3dIVIVHM6zlKfhzJdwLe37JGAiweEPztLhhsCWXs/L92ngD7MscDHEc807rjBu8UvhrV59uy435vOcvWnd5Fq6kU=
    -
      # LTD_AWS_SECRET
      secure: uWUojyUs/9ac8bmfD9A76yC2uQzdk3jNRISEYuXSL1bhASiTdsufP0ri+bWDUbn3yExwhh6pfxtbfDWSU1Ivxe2sBOCyY9yfi2iIzagF69IWI8UtBuTHnlILa/PXDc8lE85CtpKWtQJ209K/tdFTK5xe3FYbKLSLbs8YjWYW0X3SG+SoFk2z6Dr1aBWfVbJbX0dgt5/iTnEHQNGVglNcbtmsK1uNuEc9SBiuO3ilhwRFZfrJVZWwU8SjdDxdF5VOU15cNy6anJ8krXKXiBc3dkzLf38l0N5iixxSQar8EfyTg79jtsD1YlSH7ItQep8uWE2hsszsQ7QFE0fnvi1FaT5FdFqLra/3wseEy67WTjjdfCKvwJ1n9TCDM9vwp6WUv0eUFOf9TjA0tg5CPL/1iNYymhfQnaPXfKyeceMNUHB9zZa07d1H1t9dpp8caj3uDvBeAlAgeKRiJ68CE7kTd2+ilQVk0ilM5wIoZ/IvzPXu81hvyYu5/W4gGQaDf+HclA1voWgg64FgKOYOGCH/8OtudIvLWJUa9lCta2ysgf0hAOYLzTShZ7U6pcrRBwAvCZwMK62E8BWdoIz/gCsgtv3+gybVdvuJDU099aBxL0pdFu0wi+lT057omDlmrRDAI4yNGE2aiYU9NKY1U/RCubJoh50Unha9BClb+4G6JRU=
    -
      # LTD_USERNAME
      secure: FG0fpv5/4mjzSwgWpPTciizIhwcr7E3ifIVE7VzBYSu3TL1BzU9Cn1OfvMn+sqFO26XVIB9nzyX3K7nhGBXCcfYPy8nk9OzX/LUr7LktH1WMUJqg3rMyhfTl56310BdfwsGc3FV1E1F6PXiZbILi7ZynIs+wb2zF4lbD2pMHO5MEjML0nLtrtwMWxQs/t+oP/r80qG2Y6OQJ4lho9Z7CZ0t6xT3++0/557ZDrwuETw4b3u+Ti/QOIhRzIWQvNjKS9m0viFMAnxydyvmMDP7PPqc9jBSJ4Vkb7Z9qpQI1P/OxYpSnRYq/t4b93g9bCbWJ6xFCtKlFLeqOcVnXk5gsqybrOsJ7V7bQOeB4atdmesUUIrXBPuqtDWwdcAdwQhjZZkpeldJwfPuj0YT9Hlomu9mpM2b9HKrI7EHeiIOMHG4ye3HyYWzK5kA8hlSJ3kRFzQ/xzpVYtosHjXcF9cnrou2aACyWv04UO2n/3Pp9OUxYTD7ARbxXiq4sFriAsuAb+VyXmZTfdudqULLSPSXM/l6stqaaUYs7RR0dkhV3bEMkpDPqociERIshfxDAkAWPbXm3WhVieWLeZTVoZUH/fjHGW/jTdUbBtlqfZYAzV2S3D+8Izz2kq+iuT+rQsjjowrTSCxFQ9qf1sMjYSDkm7Mhly4uaYxiizU2L1DCegI4=
    -
      # LTD_PASSWORD
      secure: isa2RiZ5XGBreFLYaSz7H5WfU8GqFtA4KXZ3gJYO6J3bN9eKx9qwaNutNvvlO3cfOAggihR/fTfqM8MebiIaH3mzDAqSxS2V/Bxw4Q0ti/E73LeerR5RA2j0oFxjcgQ6+2zOgxfbzJ8lDBU3bKS+THPdQmFN9+/V0RSP0mDdZXJc/XgvLRURLz9x3G1J1Q+Hqwr9x+CfSc8z1idUD4wHYBQfjlWwuM1i/HQrL3i3q04IaCyZxNpt4RJoy75UDYf3A6HRF4izhvUFKCYNRjeJOZgQEiMMChGK8Z8O/yAb1d2IzZq9/umuOqS/2M/SznI2Revc7Sk4oQKAsLsvnOQfSsybJYYeTD5qB32gIa1mykNcwDq5Zb7hc8q5KYgm7nqHPH0wP6/iSNjCCsvteMkP9Rhdiapf+qJSDNAV16f3FhxADtk0Ir0BWLUHF5TLCcr27jJVx4/bJ1P59ppjs1N47v31eX8dfgdqoPi8C7KJU62vfDFpUKpujX1qdNqxMLRMGecE/vRPLCoA7balRh5L8vN5/Brov6uKhOa2+WV14tEC/P9Hc/JO9cPn8pUSul1O6TU4RYjORJAj+BONXATlfjoLJTVyBJI8Kd5UDkdVohjWH/ajkWFgApHJ/L7uUZQGLILUZnv+YCHY1HP7CFQVTBApjYHDwHBikwh14mlkdZk=
